wandb_version: 1

datasets:
  desc: null
  value: pacs
hparams:
  desc: null
  value: 0
kd_algos:
  desc: null
  value: no_kd
trials:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.6
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704770232.689376
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.9.6
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
