
sweep_config: 
  metric:
    name: "val_loss"
    goal: "minimize"
  method: "grid"
sweep_parameters:
  kd_algos: 
    - "FOND"
  datasets:
    - "PACS"
  overlaps:
    - "high"
    - "low"
  n_trials: 3
  n_hparams: 5
experiment_parameters:
  overall_seed: 1
  data_dir: "data"
  num_workers: 4    
  holdout_fraction: 0.2
  n_steps: 5001
  checkpoint_freq: 300
wandb:
  entity: "critical-ml-dg"
  project: "fond-teacher"
