sweep_config: 
  metric:
    name: "val/nacc"
    goal: "maximize"
  method: "grid"
sweep_parameters:
  kd_algos: 
    - "ERM"
  datasets:
    - "OfficeHome"
  num_classes:
    - 5
    - 25
  overlaps: 
    - Null
  n_trials: 3
  n_hparams: 5
experiment_parameters:
  num_domain_linked_classes: 5
  overall_seed: 1
  data_dir: "data"
  log_dir: "logs"
  num_workers: 4    
  holdout_fraction: 0.2
  n_steps: 5001
  checkpoint_freq: 300
  model_checkpoint:
    metric: "val/nacc"
    maximize: True
wandb:
  entity: "critical-ml-dg"
  project: "fond-teacher"
